blank_issues_enabled: false
contact_links:
  - name: Feedback email
    url: mailto:iamlooker@proton.me?subject=Kenko+Feedback
    about: 'Do not spam'
  - name: Telegram Community (Droid-ify)
    url: https://t.me/droidifyc
    about: 'Join our Telegram community group!'
